# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ipredict.gen_code import ipredict_interface_v1_pb2 as ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2


class CostSenseIPredictTrainingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMetrics = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/PushMetrics',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.PushMetricsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CurrentStatus = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/CurrentStatus',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusRequest.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusResponse.FromString,
                )
        self.DeleteTable = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/DeleteTable',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.DeleteTableRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CostSenseIPredictTrainingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurrentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostSenseIPredictTrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMetrics,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.PushMetricsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CurrentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CurrentStatus,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusRequest.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTable,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.DeleteTableRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cazelabs.costsense.apis.v1.CostSenseIPredictTraining', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CostSenseIPredictTraining(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/PushMetrics',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.PushMetricsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CurrentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/CurrentStatus',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusRequest.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredictTraining/DeleteTable',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.DeleteTableRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CostSenseIPredictStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trend = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/Trend',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendRes.FromString,
                )
        self.Anomaly = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/Anomaly',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyRes.FromString,
                )
        self.AnomalyReport = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/AnomalyReport',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportRes.FromString,
                )
        self.Budget = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/Budget',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetRes.FromString,
                )
        self.NewBudget = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/NewBudget',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetRes.FromString,
                )
        self.NewPrice = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.CostSenseIPredict/NewPrice',
                request_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceReq.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceRes.FromString,
                )


class CostSenseIPredictServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Anomaly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnomalyReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Budget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostSenseIPredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Trend': grpc.unary_unary_rpc_method_handler(
                    servicer.Trend,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendRes.SerializeToString,
            ),
            'Anomaly': grpc.unary_unary_rpc_method_handler(
                    servicer.Anomaly,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyRes.SerializeToString,
            ),
            'AnomalyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AnomalyReport,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportRes.SerializeToString,
            ),
            'Budget': grpc.unary_unary_rpc_method_handler(
                    servicer.Budget,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetRes.SerializeToString,
            ),
            'NewBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.NewBudget,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetRes.SerializeToString,
            ),
            'NewPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.NewPrice,
                    request_deserializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceReq.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cazelabs.costsense.apis.v1.CostSenseIPredict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CostSenseIPredict(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/Trend',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.TrendRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Anomaly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/Anomaly',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnomalyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/AnomalyReport',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.AnomalyReportRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Budget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/Budget',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.BudgetRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/NewBudget',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewBudgetRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.CostSenseIPredict/NewPrice',
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceReq.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__interface__v1__pb2.NewPriceRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
