// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: ipredict/gen_code/ipredict-forecast.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Forecast_GetJobStatus_FullMethodName = "/cazelabs.costsense.apis.v1.forecast/GetJobStatus"
)

// ForecastClient is the client API for Forecast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC Service
type ForecastClient interface {
	GetJobStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobStatusUpdate, error)
}

type forecastClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastClient(cc grpc.ClientConnInterface) ForecastClient {
	return &forecastClient{cc}
}

func (c *forecastClient) GetJobStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobStatusUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusUpdate)
	err := c.cc.Invoke(ctx, Forecast_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastServer is the server API for Forecast service.
// All implementations must embed UnimplementedForecastServer
// for forward compatibility
//
// gRPC Service
type ForecastServer interface {
	GetJobStatus(context.Context, *emptypb.Empty) (*JobStatusUpdate, error)
	mustEmbedUnimplementedForecastServer()
}

// UnimplementedForecastServer must be embedded to have forward compatible implementations.
type UnimplementedForecastServer struct {
}

func (UnimplementedForecastServer) GetJobStatus(context.Context, *emptypb.Empty) (*JobStatusUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedForecastServer) mustEmbedUnimplementedForecastServer() {}

// UnsafeForecastServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastServer will
// result in compilation errors.
type UnsafeForecastServer interface {
	mustEmbedUnimplementedForecastServer()
}

func RegisterForecastServer(s grpc.ServiceRegistrar, srv ForecastServer) {
	s.RegisterService(&Forecast_ServiceDesc, srv)
}

func _Forecast_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forecast_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServer).GetJobStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Forecast_ServiceDesc is the grpc.ServiceDesc for Forecast service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forecast_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cazelabs.costsense.apis.v1.forecast",
	HandlerType: (*ForecastServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobStatus",
			Handler:    _Forecast_GetJobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipredict/gen_code/ipredict-forecast.proto",
}
