# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipredict/gen_code/ipredict-forecast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)ipredict/gen_code/ipredict-forecast.proto\x12\x1a\x63\x61zelabs.costsense.apis.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x80\x01\n\x0fJobStatusUpdate\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12;\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\'.cazelabs.costsense.apis.v1.ForecastingR\x04\x64\x61ta\"\xa5\x01\n\x0b\x46orecasting\x12\x1c\n\tstartTime\x18\x01 \x01(\x03R\tstartTime\x12\x18\n\x07\x65ndTime\x18\x02 \x01(\x03R\x07\x65ndTime\x12\x1a\n\x08\x65xpected\x18\x03 \x01(\x01R\x08\x65xpected\x12 \n\x0b\x65xpectedMax\x18\x04 \x01(\x01R\x0b\x65xpectedMax\x12 \n\x0b\x65xpectedMin\x18\x05 \x01(\x01R\x0b\x65xpectedMin2_\n\x08\x66orecast\x12S\n\x0cGetJobStatus\x12\x16.google.protobuf.Empty\x1a+.cazelabs.costsense.apis.v1.JobStatusUpdateB\xba\x01Z)github.com/cazelabs/cost-sense/libs/go;v1\x92\x41\x8b\x01\x12s\n\x0f\x43ost Sense APIs\"Y\n\x12\x43ost Sense Project\x12&https://github.com/cazelabs/cost-sense\x1a\x1bteam.costsense@cazelabs.com2\x05\x31.0.0*\x02\x01\x02\x32\x10\x61pplication/jsonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipredict.gen_code.ipredict_forecast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/cazelabs/cost-sense/libs/go;v1\222A\213\001\022s\n\017Cost Sense APIs\"Y\n\022Cost Sense Project\022&https://github.com/cazelabs/cost-sense\032\033team.costsense@cazelabs.com2\0051.0.0*\002\001\0022\020application/json'
  _JOBSTATUSUPDATE._serialized_start=277
  _JOBSTATUSUPDATE._serialized_end=405
  _FORECASTING._serialized_start=408
  _FORECASTING._serialized_end=573
  _FORECAST._serialized_start=575
  _FORECAST._serialized_end=670
# @@protoc_insertion_point(module_scope)
