# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ipredict.gen_code import ipredict_forecast_pb2 as ipredict_dot_gen__code_dot_ipredict__forecast__pb2


class forecastStub(object):
    """gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJobStatus = channel.unary_unary(
                '/cazelabs.costsense.apis.v1.forecast/GetJobStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ipredict_dot_gen__code_dot_ipredict__forecast__pb2.JobStatusUpdate.FromString,
                )


class forecastServicer(object):
    """gRPC Service
    """

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_forecastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ipredict_dot_gen__code_dot_ipredict__forecast__pb2.JobStatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cazelabs.costsense.apis.v1.forecast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class forecast(object):
    """gRPC Service
    """

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cazelabs.costsense.apis.v1.forecast/GetJobStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ipredict_dot_gen__code_dot_ipredict__forecast__pb2.JobStatusUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
